serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${irsa_role_arn}"

configuration:
  provider: aws
  backupStorageLocation:
    name: default
    bucket: your-velero-backup-bucket
    config:
      region: ap-northeast-2

credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = YOUR_KEY
      aws_secret_access_key = YOUR_SECRET
