kind: pipeline
type: docker
name: deploy-for-main

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ec2_host
      username: ubuntu
      key:
        from_secret: ssh_private_key
      port: 22
      script:
        - cd /home/ubuntu/Chick-pay-2nd
        - git fetch origin
        - git pull origin main
        - docker-compose down
        - docker-compose up -d --build
    timeout: 300

trigger:
  branch:
    - main
