kind: pipeline
type: docker
name: deploy-for-main


  # 1. ECR에 새 이미지 빌드 & 푸시
steps:
@@ -22,6 +23,12 @@
      branch:
        - main
  # 2. ECS 서비스 업데이트 2
  - name: deploy-ecs
@@ -93,11 +100,11 @@
          echo "✅ 보안 분석 통과: 심각한 취약점이 없습니다. 계속 진행합니다."
          fi

#   # 6. 부하 테스트 + locust 결과 체크 
  - name: locust-load-test
    image: python:3.11
    environment:
      PGHOST: 
        from_secret: dbhost
      PGUSER: postgres
      PGPASSWORD:
@@ -123,21 +130,21 @@

        echo "🧪 Locust 부하 테스트 시작"
        locust --headless -f locustfile.py -u 28 -r 5 -t 30s --host https://chick-pay.com --csv=locust_result 
        
        wait 
        
        echo "📤 DB 커넥션 로그 출력 ==============================="
        cat db_conn_log.txt
      - python check_locust_result.py

# # Drone UI에서 로그 확인하는 컨테이너 
  - name: show-locust-csv
    image: python:3.11
    commands:
    - pip install pandas
    - python -c "import pandas as pd; df = pd.read_csv('locust_result_stats.csv'); print('📊 LOCUST 결과 =========================='); print(df.to_string())"

# # 부하 테스트 후 커넥션 누수 확인
  - name: monitor-db-end
    image: postgres:14
    environment:
@@ -164,9 +171,9 @@
          echo "❌ conn_count가 숫자가 아님 → '$conn_count'"
          exit 1
        fi
trigger:
  branch:
    - main
    - feat/drone
    - feat/infra