version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://test:test@user-db:5432/user_db
      - DATABASE_HOST=user-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=user_db
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test
    depends_on:
      - user-db
    networks:
      - backend

  front-service:
    build: ./front-service
    ports:
      - "8000:8000"
    volumes:
      - ./front-service:/app
    environment:
      - USER_SERVICE_URL=http://user-service:8001
    depends_on:
      - user-service
    networks:
      - backend

  user-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=user_db
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  user-db-data:
