services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 my_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend
    restart:
      - always

networks:
  backend:
    driver: bridge
