receivers:
  filelog:
    include: [/app/logs/transactions.log]
    start_at: beginning

exporters:
  awscloudwatchlogs:
    region: ap-northeast-2
    log_group_name: /django/chickpay
    log_stream_name: transaction-stream

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [awscloudwatchlogs]
