apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::297195401389:role/EKSNodeRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::297195401389:user/sujin
      username: sujin
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system


