apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transaction-postgres
spec:
  serviceName: transaction-postgres
  replicas: 1
  selector:
    matchLabels:
      app: transaction-postgres
  template:
    metadata:
      labels:
        app: transaction-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: transaction_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: transaction-postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transaction-postgres-secrets
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2