apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 297195401389.dkr.ecr.ap-northeast-2.amazonaws.com/zapp/user-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "user_service.settings"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: user-postgres-secrets
                  key: database-url
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: KAFKA_USERNAME
              value: "user1"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-user-passwords
                  key: client-passwords
            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
